### ISSUE TITLE
empty list returned in key frame detection

### ISSUE THREAD

**Issue by pritamqu** [keplerlab/katna#5] opened 2020-09-29 19:24 UTC
I tried to use this module to detect keyframes, it's returning me an empty list? can you tell me what is the possible reason for that?

**Comment by mayank10j** [comment] 2020-10-01 08:38
Which video you used for testing ? For replicating issue, can you test on video katna_repo/tests/data/pos_video.mp4 and see if you are getting empty list their as well ?

**Comment by pritamqu** [comment] 2020-10-01 16:42
I was using iemocap dataset. I think it was giving empty list as it has very less movement across the video clip.

**Comment by mayank10j** [comment] 2020-10-06 09:31
Closing issue as it seems problem was with input video

**Closed by mayank10j** 2020-10-06 09:31 UTC

**Comment by nico00** [comment] 2020-10-22 12:19
I have a similar problem with the attached video (with other videos I have no problems).
[test.mp4.zip](https://github.com/keplerlab/katna/files/5422634/test.mp4.zip)
Probably the issue is caused by less movement across the video but I don't see why this should block Katna returning keyframes (for instance best frames based on blur detection).

**Comment by thealokkr** [comment] 2020-10-23 06:41
> I have a similar problem with the attached video (with other videos I have no problems).
> [test.mp4.zip](https://github.com/keplerlab/katna/files/5422634/test.mp4.zip)
> Probably the issue is caused by less movement across the video but I don't see why this should block Katna returning keyframes (for instance best frames based on blur detection).

Hi, Now that two people have reported it. we will take a look. Would it be possible for you to share the video?

**Comment by nico00** [comment] 2020-10-23 06:44
Video has been included with the message. Let me know if you want me to share it in a different way.

**Comment by thealokkr** [comment] 2020-10-23 06:45
> Video has been included with the message. Let me know if you want me to share it in a different way.

Thank you ... i can see it now
